package reporting

import (
	"errors"
	"slices"
	"time"

	"github.com/TwiN/gatus/v5/security"
)

const (
	defaultSLATargetPercent = 99.9
	defaultFooterText       = "Generated by Gatus Automated SLA Monitoring"
	MaxDateRangeDays        = 90
)

var (
	ErrInvalidPeriod                  = errors.New("invalid reporting period: must contain only '90d', '60d', '30d', '7d', '1d', or '1h' without duplicates")
	ErrInvalidDefaultPeriod           = errors.New("invalid reporting default-period: must be included in allowed-periods")
	ErrInvalidSLATargetPercent        = errors.New("invalid reporting sla-target-percent: must be greater than 0 and at most 100")
	ErrInvalidUptimeSLATargetPercent  = errors.New("invalid reporting uptime-sla-target-percent: must be greater than 0 and at most 100")
	ErrInvalidLatencySLATargetPercent = errors.New("invalid reporting latency-sla-target-percent: must be greater than 0 and at most 100")
	ErrInvalidTimezone                = errors.New("invalid reporting timezone")
)

var defaultAllowedPeriods = []string{"90d", "30d", "7d", "1d", "1h"}
var validAllowedPeriods = []string{"90d", "60d", "30d", "7d", "1d", "1h"}

// Config configures optional report outputs.
type Config struct {
	PDF *PDFConfig `yaml:"pdf,omitempty"`
}

// PDFConfig configures on-demand customer SLA reports.
type PDFConfig struct {
	Enabled                 *bool    `yaml:"enabled,omitempty"`
	Title                   string   `yaml:"title,omitempty"`
	Logo                    string   `yaml:"logo,omitempty"`
	Timezone                string   `yaml:"timezone,omitempty"`
	AllowedPeriods          []string `yaml:"allowed-periods,omitempty"`
	DefaultPeriod           string   `yaml:"default-period,omitempty"`
	UptimeSLATargetPercent  float64  `yaml:"uptime-sla-target-percent,omitempty"`
	LatencySLATargetPercent float64  `yaml:"latency-sla-target-percent,omitempty"`
	SLATargetPercent        float64  `yaml:"sla-target-percent,omitempty"`
	FooterText              string   `yaml:"footer-text,omitempty"`
	// SuperAdmin supplies the credentials required to download a PDF report.
	SuperAdmin *security.BasicConfig `yaml:"super-admin,omitempty"`
}

func boolPointer(value bool) *bool {
	return &value
}

// IsEnabled reports whether PDF report generation is enabled.
func (cfg *PDFConfig) IsEnabled() bool {
	return cfg != nil && cfg.Enabled != nil && *cfg.Enabled
}

// ValidateAndSetDefaults validates the report configuration and supplies safe defaults.
func (cfg *PDFConfig) ValidateAndSetDefaults() error {
	if cfg == nil || !cfg.IsEnabled() {
		return nil
	}
	// Omitted credentials disable downloads at the route; malformed configured credentials fail startup.
	if cfg.SuperAdmin != nil && !cfg.SuperAdmin.IsValid() {
		return security.ErrInvalidBasicConfig
	}
	if cfg.Title == "" {
		cfg.Title = "Service SLA Report"
	}
	if cfg.FooterText == "" {
		cfg.FooterText = defaultFooterText
	}
	if cfg.Timezone == "" {
		cfg.Timezone = "UTC"
	}
	if _, err := time.LoadLocation(cfg.Timezone); err != nil {
		return ErrInvalidTimezone
	}
	if cfg.AllowedPeriods == nil {
		cfg.AllowedPeriods = append([]string(nil), defaultAllowedPeriods...)
	}
	seen := make(map[string]bool, len(cfg.AllowedPeriods))
	for _, period := range cfg.AllowedPeriods {
		if !slices.Contains(validAllowedPeriods, period) || seen[period] {
			return ErrInvalidPeriod
		}
		seen[period] = true
	}
	if cfg.DefaultPeriod == "" {
		cfg.DefaultPeriod = cfg.AllowedPeriods[0]
	}
	if !slices.Contains(cfg.AllowedPeriods, cfg.DefaultPeriod) {
		return ErrInvalidDefaultPeriod
	}
	if cfg.UptimeSLATargetPercent == 0 {
		if cfg.SLATargetPercent > 0 {
			cfg.UptimeSLATargetPercent = cfg.SLATargetPercent
		} else {
			cfg.UptimeSLATargetPercent = defaultSLATargetPercent
		}
	}
	if cfg.LatencySLATargetPercent == 0 {
		if cfg.SLATargetPercent > 0 {
			cfg.LatencySLATargetPercent = cfg.SLATargetPercent
		} else {
			cfg.LatencySLATargetPercent = defaultSLATargetPercent
		}
	}
	if cfg.SLATargetPercent == 0 {
		cfg.SLATargetPercent = cfg.UptimeSLATargetPercent
	}
	if cfg.UptimeSLATargetPercent <= 0 || cfg.UptimeSLATargetPercent > 100 {
		return ErrInvalidUptimeSLATargetPercent
	}
	if cfg.LatencySLATargetPercent <= 0 || cfg.LatencySLATargetPercent > 100 {
		return ErrInvalidLatencySLATargetPercent
	}
	return nil
}

// ValidateAndSetDefaults validates nested report output configurations.
func (cfg *Config) ValidateAndSetDefaults() error {
	if cfg == nil || cfg.PDF == nil {
		return nil
	}
	return cfg.PDF.ValidateAndSetDefaults()
}
