package report

import (
	"bytes"
	_ "embed"
	"fmt"
	"image"
	_ "image/gif"
	_ "image/jpeg"
	"image/png"
	"io"
	"math"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/TwiN/gatus/v5/client"
	"github.com/signintech/gopdf"
)

//go:embed assets/DejaVuSans.ttf
var reportFont []byte

// Document contains the SLA information rendered into a downloadable PDF.
type Document struct {
	Title            string
	Logo             string
	Period           string
	GeneratedAt      time.Time
	UptimeSLATarget  float64
	LatencySLATarget float64
	SLATarget        float64 // backwards-compatible fallback
	FooterText       string
	Endpoints        []EndpointStatistics
}

// EndpointStatistics contains the SLA metrics and metadata for an endpoint.
type EndpointStatistics struct {
	Name           string
	Group          string
	Type           string
	URL            string
	UptimePercent  float64
	LatencyPercent float64
}

const (
	pageWidth   = 841.89
	pageHeight  = 595.28
	marginSide  = 40.0
	usableWidth = pageWidth - (marginSide * 2) // 761.89
	bottomLimit = 545.0
)

// GeneratePDF creates a comprehensive landscape SLA scorecard with summary KPIs,
// comparative availability/latency compliance charts, and an endpoint breakdown table.
func GeneratePDF(document Document) ([]byte, error) {
	var pdf gopdf.GoPdf
	pdf.Start(gopdf.Config{PageSize: *gopdf.PageSizeA4Landscape})

	fontRegistered := false
	setupPage := func() error {
		pdf.AddPage()
		if !fontRegistered {
			if err := pdf.AddTTFFontData("report", reportFont); err != nil {
				return err
			}
			fontRegistered = true
		}
		return nil
	}

	if err := setupPage(); err != nil {
		return nil, err
	}

	title := document.Title
	if title == "" {
		title = "Service SLA Report"
	}
	uptimeTarget := document.UptimeSLATarget
	if uptimeTarget <= 0 {
		if document.SLATarget > 0 {
			uptimeTarget = document.SLATarget
		} else {
			uptimeTarget = 99.9
		}
	}
	latencyTarget := document.LatencySLATarget
	if latencyTarget <= 0 {
		if document.SLATarget > 0 {
			latencyTarget = document.SLATarget
		} else {
			latencyTarget = 99.9
		}
	}
	footerText := document.FooterText
	if footerText == "" {
		footerText = "Generated by Gatus Automated SLA Monitoring"
	}

	var logoHolder gopdf.ImageHolder
	if document.Logo != "" {
		if holder, err := loadLogoImage(document.Logo); err == nil {
			logoHolder = holder
		}
	}

	// 1. Header
	renderHeader(&pdf, title, document.Period, document.GeneratedAt, logoHolder)

	// 2. Summary KPI Cards
	renderKPICards(&pdf, document.Endpoints, uptimeTarget, latencyTarget, 82)

	// 3. Side-by-side Comparative Charts
	renderComparativeCharts(&pdf, document.Endpoints, uptimeTarget, latencyTarget, 144)

	// 4. Detailed Breakdown Table
	currentPage := 1
	err := renderEndpointTable(&pdf, document.Endpoints, uptimeTarget, latencyTarget, footerText, 318, &currentPage, func() error {
		currentPage++
		if err := setupPage(); err != nil {
			return err
		}
		renderHeaderSmall(&pdf, title, document.Period, document.GeneratedAt, uptimeTarget, latencyTarget, logoHolder)
		return nil
	})
	if err != nil {
		return nil, err
	}

	return pdf.GetBytesPdfReturnErr()
}

func loadLogoImage(logo string) (gopdf.ImageHolder, error) {
	if logo == "" {
		return nil, nil
	}
	var data []byte
	if strings.HasPrefix(logo, "http://") || strings.HasPrefix(logo, "https://") {
		httpClient := client.GetHTTPClient(nil)
		req, err := http.NewRequest(http.MethodGet, logo, http.NoBody)
		if err != nil {
			return nil, err
		}
		resp, err := httpClient.Do(req)
		if err != nil {
			return nil, err
		}
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("fetch logo: %s", resp.Status)
		}
		data, err = io.ReadAll(resp.Body)
		if err != nil {
			return nil, err
		}
	} else {
		var err error
		data, err = os.ReadFile(logo)
		if err != nil {
			return nil, err
		}
	}
	if len(data) == 0 {
		return nil, nil
	}
	img, _, err := image.Decode(bytes.NewReader(data))
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		return nil, err
	}
	return gopdf.ImageHolderByBytes(buf.Bytes())
}

func renderHeader(pdf *gopdf.GoPdf, title, period string, generatedAt time.Time, logoHolder gopdf.ImageHolder) {
	titleX := marginSide
	titleY := 32.0
	metadataY := 50.0
	if logoHolder != nil {
		const iconSize = 26.0
		logoRect := &gopdf.Rect{W: iconSize, H: iconSize}
		_ = pdf.ImageByHolder(logoHolder, marginSide, 32, logoRect)
		titleX = marginSide + iconSize + 10
		// gopdf positions text by its baseline; lower the text block into the logo bounds.
		titleY = 47
		metadataY = 59
	}

	// Report Title
	_ = pdf.SetFont("report", "", 16)
	pdf.SetTextColor(15, 23, 42) // slate-900
	pdf.SetX(titleX)
	pdf.SetY(titleY)
	_ = pdf.Text(title)

	// Subtitle / Metadata
	_ = pdf.SetFont("report", "", 8)
	pdf.SetTextColor(100, 116, 139) // slate-500
	pdf.SetX(titleX)
	pdf.SetY(metadataY)
	metaText := fmt.Sprintf("Reporting Period: %s    |    Generated: %s",
		periodLabel(period),
		generatedAt.Format("02 Jan 2006 15:04 MST"),
	)
	_ = pdf.Text(metaText)

	// Divider line
	pdf.SetStrokeColor(226, 232, 240) // slate-200
	pdf.SetLineWidth(0.75)
	pdf.Line(marginSide, 68, marginSide+usableWidth, 68)
}

func renderHeaderSmall(pdf *gopdf.GoPdf, title, period string, generatedAt time.Time, uptimeTarget, latencyTarget float64, logoHolder gopdf.ImageHolder) {
	titleX := marginSide
	if logoHolder != nil {
		logoRect := &gopdf.Rect{W: 14, H: 14}
		_ = pdf.ImageByHolder(logoHolder, marginSide, 26, logoRect)
		titleX = marginSide + 18
	}

	_ = pdf.SetFont("report", "", 11)
	pdf.SetTextColor(15, 23, 42)
	pdf.SetX(titleX)
	pdf.SetY(28)
	_ = pdf.Text(fmt.Sprintf("%s — %s (Uptime: %.2f%%, Latency: %.2f%%)", title, periodLabel(period), uptimeTarget, latencyTarget))

	_ = pdf.SetFont("report", "", 8)
	pdf.SetTextColor(100, 116, 139)
	pdf.SetX(marginSide + usableWidth - 150)
	pdf.SetY(28)
	_ = pdf.Text(generatedAt.Format("02 Jan 2006 15:04 MST"))

	pdf.SetStrokeColor(226, 232, 240)
	pdf.SetLineWidth(0.75)
	pdf.Line(marginSide, 42, marginSide+usableWidth, 42)
}

func renderKPICards(pdf *gopdf.GoPdf, endpoints []EndpointStatistics, uptimeTarget, latencyTarget float64, y float64) {
	const cardHeight = 48.0
	const gap = 12.0
	cardWidth := (usableWidth - (gap * 3)) / 4.0

	var totalUptime, totalLatency float64
	metCount := 0
	count := len(endpoints)

	for _, ep := range endpoints {
		totalUptime += ep.UptimePercent
		totalLatency += ep.LatencyPercent
		if ep.UptimePercent >= uptimeTarget && ep.LatencyPercent >= latencyTarget {
			metCount++
		}
	}

	avgUptime := 0.0
	avgLatency := 0.0
	if count > 0 {
		avgUptime = totalUptime / float64(count)
		avgLatency = totalLatency / float64(count)
	}

	cards := []struct {
		Label    string
		Value    string
		Subtext  string
		IsMet    bool
		HasState bool
	}{
		{
			Label:    "Average Uptime",
			Value:    formatPercentOrNA(avgUptime, count > 0),
			Subtext:  fmt.Sprintf("Target: %.2f%%", uptimeTarget),
			IsMet:    avgUptime >= uptimeTarget,
			HasState: count > 0,
		},
		{
			Label:    "Avg Latency Compliance",
			Value:    formatPercentOrNA(avgLatency, count > 0),
			Subtext:  fmt.Sprintf("Target: %.2f%%", latencyTarget),
			IsMet:    avgLatency >= latencyTarget,
			HasState: count > 0,
		},
		{
			Label:    "Total Endpoints",
			Value:    fmt.Sprintf("%d", count),
			Subtext:  "Active monitors",
			IsMet:    true,
			HasState: false,
		},
		{
			Label: "SLA Compliance Rate",
			Value: func() string {
				if count == 0 {
					return "N/A"
				}
				return fmt.Sprintf("%d / %d Met", metCount, count)
			}(),
			Subtext: func() string {
				if count == 0 {
					return "No active endpoints"
				}
				pct := (float64(metCount) / float64(count)) * 100
				return fmt.Sprintf("%.1f%% meeting target", pct)
			}(),
			IsMet:    metCount == count && count > 0,
			HasState: count > 0,
		},
	}

	for i, card := range cards {
		x := marginSide + float64(i)*(cardWidth+gap)

		// Card background & border
		pdf.SetFillColor(248, 250, 252) // slate-50
		pdf.RectFromUpperLeftWithStyle(x, y, cardWidth, cardHeight, "F")
		pdf.SetStrokeColor(226, 232, 240) // slate-200
		pdf.SetLineWidth(0.75)
		pdf.RectFromUpperLeftWithStyle(x, y, cardWidth, cardHeight, "D")

		// Left accent bar
		if card.HasState {
			if card.IsMet {
				pdf.SetFillColor(22, 163, 74) // emerald-600
			} else {
				pdf.SetFillColor(220, 38, 38) // red-600
			}
			pdf.RectFromUpperLeftWithStyle(x, y, 3.5, cardHeight, "F")
		}

		// Card Label
		_ = pdf.SetFont("report", "", 7.5)
		pdf.SetTextColor(100, 116, 139) // slate-500
		pdf.SetX(x + 12)
		pdf.SetY(y + 13)
		_ = pdf.Text(card.Label)

		// Card Value
		_ = pdf.SetFont("report", "", 13)
		if card.HasState {
			if card.IsMet {
				pdf.SetTextColor(22, 101, 52) // emerald-800
			} else {
				pdf.SetTextColor(185, 28, 28) // red-700
			}
		} else {
			pdf.SetTextColor(15, 23, 42) // slate-900
		}
		pdf.SetX(x + 12)
		pdf.SetY(y + 29)
		_ = pdf.Text(card.Value)

		// Card Subtext
		_ = pdf.SetFont("report", "", 7)
		pdf.SetTextColor(148, 163, 184) // slate-400
		pdf.SetX(x + 12)
		pdf.SetY(y + 40)
		_ = pdf.Text(card.Subtext)
	}
}

func renderComparativeCharts(pdf *gopdf.GoPdf, endpoints []EndpointStatistics, uptimeTarget, latencyTarget, y float64) {
	const gap = 12.0
	panelWidth := (usableWidth - gap) / 2.0
	const panelHeight = 162.0

	// Left: Uptime Chart
	renderSingleChart(pdf, "Uptime Availability", "Service uptime vs SLA target", endpoints, uptimeTarget, marginSide, y, panelWidth, panelHeight, func(ep EndpointStatistics) float64 {
		return ep.UptimePercent
	})

	// Right: Latency Compliance Chart
	renderSingleChart(pdf, "Latency Compliance", "Threshold response time compliance", endpoints, latencyTarget, marginSide+panelWidth+gap, y, panelWidth, panelHeight, func(ep EndpointStatistics) float64 {
		return ep.LatencyPercent
	})
}

func renderSingleChart(pdf *gopdf.GoPdf, title, subtitle string, endpoints []EndpointStatistics, target, x, y, width, height float64, valueFn func(EndpointStatistics) float64) {
	// Container Box
	pdf.SetFillColor(255, 255, 255)
	pdf.RectFromUpperLeftWithStyle(x, y, width, height, "F")
	pdf.SetStrokeColor(226, 232, 240) // slate-200
	pdf.SetLineWidth(0.75)
	pdf.RectFromUpperLeftWithStyle(x, y, width, height, "D")

	// Header Title & Subtitle
	_ = pdf.SetFont("report", "", 10)
	pdf.SetTextColor(15, 23, 42) // slate-900
	pdf.SetX(x + 14)
	pdf.SetY(y + 16)
	_ = pdf.Text(title)

	_ = pdf.SetFont("report", "", 7)
	pdf.SetTextColor(100, 116, 139) // slate-500
	pdf.SetX(x + 14)
	pdf.SetY(y + 26)
	_ = pdf.Text(subtitle)

	// Target Badge in Top-Right of Card
	targetBadgeW := 80.0
	targetBadgeH := 14.0
	targetBadgeX := x + width - targetBadgeW - 14
	targetBadgeY := y + 12

	pdf.SetFillColor(254, 242, 242) // red-50
	pdf.RectFromUpperLeftWithStyle(targetBadgeX, targetBadgeY, targetBadgeW, targetBadgeH, "F")
	pdf.SetStrokeColor(254, 202, 202) // red-200
	pdf.SetLineWidth(0.5)
	pdf.RectFromUpperLeftWithStyle(targetBadgeX, targetBadgeY, targetBadgeW, targetBadgeH, "D")

	_ = pdf.SetFont("report", "", 6.5)
	pdf.SetTextColor(185, 28, 28) // red-700
	pdf.SetX(targetBadgeX + 6)
	pdf.SetY(targetBadgeY + 9.5)
	_ = pdf.Text(fmt.Sprintf("Target: %.2f%%", target))

	// Track layout metrics
	const trackXOffset = 124.0
	const trackWidth = 172.0
	const trackHeight = 7.0

	// Scale Header / Markers (at y + 36)
	scaleY := y + 37.0
	_ = pdf.SetFont("report", "", 6)
	pdf.SetTextColor(148, 163, 184) // slate-400

	pdf.SetX(x + 14)
	pdf.SetY(scaleY)
	_ = pdf.Text("SERVICE")

	pdf.SetX(x + trackXOffset)
	pdf.SetY(scaleY)
	_ = pdf.Text("0%")

	pdf.SetX(x + trackXOffset + (trackWidth / 2) - 6)
	pdf.SetY(scaleY)
	_ = pdf.Text("50%")

	pdf.SetX(x + trackXOffset + trackWidth - 16)
	pdf.SetY(scaleY)
	_ = pdf.Text("100%")

	pdf.SetX(x + width - 48)
	pdf.SetY(scaleY)
	_ = pdf.Text("ACTUAL")

	// Subtle header divider
	pdf.SetStrokeColor(241, 245, 249) // slate-100
	pdf.SetLineWidth(0.5)
	pdf.Line(x+14, scaleY+4, x+width-14, scaleY+4)

	// Handle Empty State
	if len(endpoints) == 0 {
		_ = pdf.SetFont("report", "", 8)
		pdf.SetTextColor(148, 163, 184)
		pdf.SetX(x + (width / 2) - 45)
		pdf.SetY(y + (height / 2) + 10)
		_ = pdf.Text("No reporting data available")
		return
	}

	// Limit to top 5 items for clean, balanced progress gauge presentation
	displayEndpoints := endpoints
	hasMore := false
	if len(displayEndpoints) > 5 {
		displayEndpoints = displayEndpoints[:5]
		hasMore = true
	}

	rowStartY := scaleY + 8.0
	rowSpacing := 18.0

	for i, ep := range displayEndpoints {
		currY := rowStartY + float64(i)*rowSpacing
		val := math.Max(0, math.Min(100, valueFn(ep)))

		// Endpoint Name
		name := ep.Name
		if len(name) > 17 {
			name = name[:15] + "…"
		}
		_ = pdf.SetFont("report", "", 7)
		pdf.SetTextColor(51, 65, 85) // slate-700
		pdf.SetX(x + 14)
		pdf.SetY(currY + 7.5)
		_ = pdf.Text(name)

		// Progress Track Background
		tX := x + trackXOffset
		tY := currY + 2.0
		pdf.SetFillColor(241, 245, 249) // slate-100
		pdf.RectFromUpperLeftWithStyle(tX, tY, trackWidth, trackHeight, "F")
		pdf.SetStrokeColor(226, 232, 240) // slate-200
		pdf.SetLineWidth(0.5)
		pdf.RectFromUpperLeftWithStyle(tX, tY, trackWidth, trackHeight, "D")

		// Progress Bar Fill
		fillWidth := math.Max(1.0, trackWidth*(val/100.0))
		if val >= target {
			pdf.SetFillColor(22, 163, 74) // emerald-600
		} else {
			pdf.SetFillColor(220, 38, 38) // red-600
		}
		pdf.RectFromUpperLeftWithStyle(tX, tY, fillWidth, trackHeight, "F")

		// Target SLA Marker Line (Needle)
		targetX := tX + trackWidth*(math.Max(0, math.Min(100, target))/100.0)
		pdf.SetStrokeColor(185, 28, 28) // red-700
		pdf.SetLineWidth(1.0)
		pdf.Line(targetX, tY-1.5, targetX, tY+trackHeight+1.5)

		// Value Text (right-aligned column)
		_ = pdf.SetFont("report", "", 7.5)
		if val >= target {
			pdf.SetTextColor(22, 101, 52) // emerald-800
		} else {
			pdf.SetTextColor(185, 28, 28) // red-700
		}
		pdf.SetX(x + width - 52)
		pdf.SetY(currY + 7.5)
		_ = pdf.Text(fmt.Sprintf("%.2f%%", val))
	}

	// Footer indicator if list is truncated in chart view
	if hasMore {
		_ = pdf.SetFont("report", "", 6)
		pdf.SetTextColor(148, 163, 184)
		pdf.SetX(x + 14)
		pdf.SetY(y + height - 8)
		_ = pdf.Text(fmt.Sprintf("+%d more services detailed in table below", len(endpoints)-5))
	}
}

func renderEndpointTable(pdf *gopdf.GoPdf, endpoints []EndpointStatistics, uptimeTarget, latencyTarget float64, footerText string, startY float64, pageNum *int, onNewPage func() error) error {
	y := startY

	// Section Title
	_ = pdf.SetFont("report", "", 10.5)
	pdf.SetTextColor(15, 23, 42)
	pdf.SetX(marginSide)
	pdf.SetY(y)
	_ = pdf.Text("Endpoint Performance Breakdown")
	y += 10

	renderTableHeader := func(currY float64) float64 {
		headerHeight := 18.0
		pdf.SetFillColor(241, 245, 249) // slate-100
		pdf.RectFromUpperLeftWithStyle(marginSide, currY, usableWidth, headerHeight, "F")
		pdf.SetStrokeColor(203, 213, 225) // slate-300
		pdf.SetLineWidth(0.5)
		pdf.RectFromUpperLeftWithStyle(marginSide, currY, usableWidth, headerHeight, "D")

		_ = pdf.SetFont("report", "", 7.5)
		pdf.SetTextColor(71, 85, 105) // slate-600

		// Column headers
		pdf.SetX(marginSide + 12)
		pdf.SetY(currY + 12)
		_ = pdf.Text("GROUP / SERVICE TIER")

		pdf.SetX(marginSide + 162)
		pdf.SetY(currY + 12)
		_ = pdf.Text("TYPE")

		pdf.SetX(marginSide + 242)
		pdf.SetY(currY + 12)
		_ = pdf.Text("ENDPOINT")

		pdf.SetX(marginSide + 467)
		pdf.SetY(currY + 12)
		_ = pdf.Text("UPTIME (%)")

		pdf.SetX(marginSide + 570)
		pdf.SetY(currY + 12)
		_ = pdf.Text("LATENCY COMPLIANCE (%)")

		pdf.SetX(marginSide + 690)
		pdf.SetY(currY + 12)
		_ = pdf.Text("SLA STATUS")

		return currY + headerHeight
	}

	y = renderTableHeader(y)

	if len(endpoints) == 0 {
		rowHeight := 24.0
		pdf.SetFillColor(255, 255, 255)
		pdf.RectFromUpperLeftWithStyle(marginSide, y, usableWidth, rowHeight, "F")
		pdf.SetStrokeColor(226, 232, 240)
		pdf.SetLineWidth(0.5)
		pdf.RectFromUpperLeftWithStyle(marginSide, y, usableWidth, rowHeight, "D")

		_ = pdf.SetFont("report", "", 8)
		pdf.SetTextColor(148, 163, 184)
		pdf.SetX(marginSide + (usableWidth / 2) - 40)
		pdf.SetY(y + 15)
		_ = pdf.Text("No endpoint records found")

		renderPageFooter(pdf, footerText, *pageNum)
		return nil
	}

	const rowHeight = 25.0
	for i, ep := range endpoints {
		if y+rowHeight > bottomLimit {
			renderPageFooter(pdf, footerText, *pageNum)
			if err := onNewPage(); err != nil {
				return err
			}
			y = renderTableHeader(50)
		}

		// Alternating row background
		if i%2 == 0 {
			pdf.SetFillColor(255, 255, 255)
		} else {
			pdf.SetFillColor(248, 250, 252) // slate-50
		}
		pdf.RectFromUpperLeftWithStyle(marginSide, y, usableWidth, rowHeight, "F")
		pdf.SetStrokeColor(241, 245, 249) // slate-100
		pdf.SetLineWidth(0.5)
		pdf.RectFromUpperLeftWithStyle(marginSide, y, usableWidth, rowHeight, "D")

		// Group Name
		groupName := ep.Group
		if groupName == "" {
			groupName = "Default"
		}
		if len(groupName) > 26 {
			groupName = groupName[:24] + "…"
		}
		_ = pdf.SetFont("report", "", 7.5)
		pdf.SetTextColor(15, 23, 42) // slate-900
		pdf.SetX(marginSide + 12)
		pdf.SetY(y + 15.0)
		_ = pdf.Text(groupName)

		// Endpoint type
		_ = pdf.SetFont("report", "", 7.5)
		pdf.SetTextColor(15, 23, 42) // slate-900
		pdf.SetX(marginSide + 162)
		pdf.SetY(y + 15.0)
		_ = pdf.Text(formatEndpointType(ep.Type))

		// Endpoint URL; use the endpoint name only when no target URL is available.
		endpoint := ep.URL
		if endpoint == "" {
			endpoint = ep.Name
		}
		if len(endpoint) > 40 {
			endpoint = endpoint[:37] + "..."
		}
		_ = pdf.SetFont("report", "", 7.5)
		pdf.SetTextColor(15, 23, 42) // slate-900
		pdf.SetX(marginSide + 242)
		pdf.SetY(y + 15.0)
		_ = pdf.Text(endpoint)

		// Uptime %
		_ = pdf.SetFont("report", "", 8)
		if ep.UptimePercent >= uptimeTarget {
			pdf.SetTextColor(22, 101, 52) // emerald-800
		} else {
			pdf.SetTextColor(185, 28, 28) // red-700
		}
		pdf.SetX(marginSide + 467)
		pdf.SetY(y + 15.0)
		_ = pdf.Text(fmt.Sprintf("%.2f%%", ep.UptimePercent))

		// Latency Compliance %
		if ep.LatencyPercent >= latencyTarget {
			pdf.SetTextColor(22, 101, 52)
		} else {
			pdf.SetTextColor(185, 28, 28)
		}
		pdf.SetX(marginSide + 570)
		pdf.SetY(y + 15.0)
		_ = pdf.Text(fmt.Sprintf("%.2f%%", ep.LatencyPercent))

		// SLA Status Badge
		isMet := ep.UptimePercent >= uptimeTarget && ep.LatencyPercent >= latencyTarget
		badgeW := 56.0
		badgeH := 14.0
		badgeX := marginSide + 690
		badgeY := y + 6.0

		if isMet {
			pdf.SetFillColor(220, 252, 231) // green-100
			pdf.RectFromUpperLeftWithStyle(badgeX, badgeY, badgeW, badgeH, "F")
			_ = pdf.SetFont("report", "", 6.5)
			pdf.SetTextColor(22, 101, 52) // green-800
			pdf.SetX(badgeX + 18)
			pdf.SetY(badgeY + 9.5)
			_ = pdf.Text("MET")
		} else {
			pdf.SetFillColor(254, 226, 226) // red-100
			pdf.RectFromUpperLeftWithStyle(badgeX, badgeY, badgeW, badgeH, "F")
			_ = pdf.SetFont("report", "", 6.5)
			pdf.SetTextColor(153, 27, 27) // red-800
			pdf.SetX(badgeX + 8)
			pdf.SetY(badgeY + 9.5)
			_ = pdf.Text("BREACHED")
		}

		y += rowHeight
	}

	renderPageFooter(pdf, footerText, *pageNum)
	return nil
}

func renderPageFooter(pdf *gopdf.GoPdf, footerText string, pageNum int) {
	const footerY = 562.0
	pdf.SetStrokeColor(226, 232, 240)
	pdf.SetLineWidth(0.5)
	pdf.Line(marginSide, footerY, marginSide+usableWidth, footerY)

	_ = pdf.SetFont("report", "", 7)
	pdf.SetTextColor(148, 163, 184) // slate-400

	pdf.SetX(marginSide)
	pdf.SetY(footerY + 11)
	_ = pdf.Text(footerText)

	pageStr := fmt.Sprintf("Page %d", pageNum)
	pdf.SetX(marginSide + usableWidth - 30)
	pdf.SetY(footerY + 11)
	_ = pdf.Text(pageStr)
}

func formatEndpointType(endpointType string) string {
	if endpointType == "" || endpointType == "UNKNOWN" {
		return "Unknown"
	}
	return strings.ToUpper(endpointType[:1]) + strings.ToLower(endpointType[1:])
}

func formatPercentOrNA(val float64, available bool) string {
	if !available {
		return "N/A"
	}
	return fmt.Sprintf("%.2f%%", val)
}

func periodLabel(period string) string {
	switch period {
	case "90d":
		return "Last 90 days"
	case "60d":
		return "Last 60 days"
	case "30d":
		return "Last 30 days"
	case "7d":
		return "Last 7 days"
	case "1d":
		return "Last 24 hours"
	case "1h":
		return "Last hour"
	}
	if period == "" {
		return "Default period"
	}
	return period
}
